### ISSUE TITLE
New 249 release.

### ISSUE THREAD

**Issue by ht990332** [systemd/systemd-stable#222]
Hello. There have been serveral checkins -nto the 249 stable branch since April.
Can we have a new release? This is the last major system release that doesn't use post 5.10LTS kernel features. linux 5.10.x is currently farthest supported kernel.

**Comment by yuwata** [comment]
The upstream basically manages the two recent releases, currently v250 and v251. So, please contact to your downstream at first.

**Comment by ht990332** [comment]
> The upstream basically manages the two recent releases, currently v250 and v251. So, please contact to your downstream at first.

This is a custom installation for work. Perhaps you can make an exception since 5.15 is only supported till 2023 which is less than 5.10?

**Comment by yuwata** [comment]
Not sure, I cannot follow, sorry. Even though we do not actively update older releases, but feel free to open a pull request about backporting upstream commits.

**Comment by ht990332** [comment]
> Not sure, I cannot follow, sorry. Even though we do not actively update older releases, but feel free to open a pull request about backporting upstream commits.

Ok, will do.

Just to be clear though:
- Linux 5.10 is supported till 2026.
- Linux 5.15 is supported till 2023.
- Systemd 250 and higher use Linux higher than 5.10. So, those who want to stay on 5.10 which is the longest supported are stuck with systemd 249 unless they backport features into 5.10 kernel which is not optimal.

**Comment by gregkh** [comment]
Why would you stay on 5.10 and not move to 5.15 or 6.1?  And why would you want to stay at 5.10 yet update systemd?

Please just move to a newer kernel version, there is no reason to stay at 5.10 at all.

And if you need/want 5.15 to last longer, please work with the kernel developers maintaining it, they have documented it quite well as to what is needed to get it to be supported longer.

**Comment by ht990332** [comment]
Hi Greg!
First of all, I wasn't trying to update systemd. I was asking for an extension on 249 support.
Regarding the kernel upgrade, there are limiting factors. People don't just upgrade production devices to a new version of an operating system at will. Jobs depend on that. It's not that easy. There are production machines still using Windows 7 and 8.1 for this very reason. I'm just trying to make the best out of an unfortunate sutation.

I do, however, understand where you are coming from. Newer kernels are more secure and maybe even faster due to code refactoring and such.

Thank you for the valuable input!

**Comment by mrc0mmand** [comment]
> > Not sure, I cannot follow, sorry. Even though we do not actively update older releases, but feel free to open a pull request about backporting upstream commits.
> 
> Ok, will do.
> 
> Just to be clear though:
> 
>     * Linux 5.10 is supported till 2026.
> 
>     * Linux 5.15 is supported till 2023.
> 
>     * Systemd 250 and higher use Linux higher than 5.10. So, those who want to stay on 5.10 which is the longest supported are stuck with systemd 249 unless they backport features into 5.10 kernel which is not optimal.

I don't think I follow here - the current recommended baseline for systemd is kernel 4.15, with which it should just work™ , see https://github.com/systemd/systemd/blob/main/README#L32, with 5.10 you should be more than fine. So what you mean by "Systemd 250 and higher use Linux higher than 5.10"?

**Comment by gregkh** [comment]
> Regarding the kernel upgrade, there are limiting factors. People don't just upgrade production devices to a new version of an operating system at will. Jobs depend on that. It's not that easy

Then get support for those long-running-and-obsolete-and-insecure systems from the vendor that is forcing you to use
them for longer than they are being supported upstream.  You pay for that services, please take advantage of it and do not
force the individual projects to support this type of insecure situtaion.

>.There are production machines still using Windows 7 and 8.1 for this very reason. 

And the vendor supports that just fine as you can pay for it.  I don't understand how that has anything to do with the community support lifecycles of open source projects.

Again, please work with your vendor if you are relying on something like this, as you are paying for it.

> I do, however, understand where you are coming from. Newer kernels are more secure and maybe even faster due to code refactoring and such.

Yes, newer kernels are always more secure, please always update to them in order to take advantage of fixes
of known issues.

But again, that has nothing to do with this type of request.  Please work with your vendor if you have questions or issues regarding how long they are going to support you.  That's not something an individual open source project can ever do for obvious reasons.
